#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include "audio_codecs/es8311_audio_codec.h"

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_3
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_4
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#endif

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_9
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SPI_SCK_PIN GPIO_NUM_1
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_2
#define DISPLAY_DC_PIN GPIO_NUM_0
#define DISPLAY_SPI_CS_PIN GPIO_NUM_21

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_20
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define UART_ECHO_TXD GPIO_NUM_13
#define UART_ECHO_RXD GPIO_NUM_12
#define UART_ECHO_RTS (-1)
#define UART_ECHO_CTS (-1)

#define ECHO_UART_PORT_NUM UART_NUM_1
#define ECHO_UART_BAUD_RATE (9600)
#define BUF_SIZE (1024)

#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0

#define EP1331S 0
#define EP1531S 0
#define EP1531T 0
#define EP1831T 1
#define E2031CP 0
#define E2431BP 0
#define E2831BP 0
#define E3231BP 0
#define E3531QP 0
#define E4031BP 0


#if EP1531S
#define DISPLAY_WIDTH 240  
#define DISPLAY_HEIGHT 240 
#define DISPLAY_MIRROR_X false 
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false 
#define DISPLAY_INVERT_COLOR false

#elif E2431BP||E2831BP ||E3231BP || E2031CP
#define DISPLAY_WIDTH 240      
#define DISPLAY_HEIGHT 320    
#define DISPLAY_MIRROR_X false 
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false 
#define DISPLAY_INVERT_COLOR false

#elif E3531QP|| E4031BP
#define DISPLAY_WIDTH 320     
#define DISPLAY_HEIGHT 480    
#define DISPLAY_MIRROR_X true 
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false 
#define DISPLAY_INVERT_COLOR true

#elif EP1831T
#define DISPLAY_WIDTH 360      
#define DISPLAY_HEIGHT 360     
#define DISPLAY_MIRROR_X false 
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false 
#define DISPLAY_INVERT_COLOR true

#elif EP1331S
#define DISPLAY_WIDTH 240     
#define DISPLAY_HEIGHT 240    
#define DISPLAY_MIRROR_X true 
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false 
#define DISPLAY_INVERT_COLOR true

#elif EP1531T
#define DISPLAY_WIDTH  360     
#define DISPLAY_HEIGHT 360    
#define DISPLAY_MIRROR_X false 
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false 
#define DISPLAY_INVERT_COLOR true

#endif // _BOARD_CONFIG_H_

