// #ifndef _BOARD_CONFIG_H_
// #define _BOARD_CONFIG_H_

// #include <driver/gpio.h>

// #define AUDIO_INPUT_SAMPLE_RATE  24000
// #define AUDIO_OUTPUT_SAMPLE_RATE 24000

// #define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
// #define AUDIO_I2S_GPIO_WS   GPIO_NUM_12
// #define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
// #define AUDIO_I2S_GPIO_DIN  GPIO_NUM_7
// #define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

// #define AUDIO_CODEC_USE_PCA9557
// #define AUDIO_CODEC_PA_PIN       GPIO_NUM_13
// #define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_0
// #define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_1
// #define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
// #define AUDIO_CODEC_ES7210_ADDR  0x82

// #define BUILTIN_LED_GPIO        GPIO_NUM_NC
// #define BOOT_BUTTON_GPIO        GPIO_NUM_9
// #define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
// #define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// #define DISPLAY_SPI_SCK_PIN     GPIO_NUM_3
// #define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_5
// #define DISPLAY_DC_PIN          GPIO_NUM_6
// #define DISPLAY_SPI_CS_PIN      GPIO_NUM_4

// #define DISPLAY_WIDTH   320
// #define DISPLAY_HEIGHT  240
// #define DISPLAY_MIRROR_X true
// #define DISPLAY_MIRROR_Y false
// #define DISPLAY_SWAP_XY true

// #define DISPLAY_OFFSET_X  0
// #define DISPLAY_OFFSET_Y  0

// #define DISPLAY_BACKLIGHT_PIN GPIO_NUM_2
// #define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

// #endif // _BOARD_CONFIG_H_
#if 0
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS GPIO_NUM_12
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_PA_PIN GPIO_NUM_13
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_0
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_1
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR 0x82

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_9
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SPI_SCK_PIN GPIO_NUM_3
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_5
#define DISPLAY_DC_PIN GPIO_NUM_6
#define DISPLAY_SPI_CS_PIN GPIO_NUM_4

#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_2
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

#endif // _BOARD_CONFIG_H_
#endif

#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include "audio_codecs/es8311_audio_codec.h"

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#if 0
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS GPIO_NUM_12
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_11

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_PA_PIN GPIO_NUM_13
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_0
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_1
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR 0x82
#else

#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_3
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_4
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_10
#define AUDIO_I2S_GPIO_WS GPIO_NUM_6
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_8
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_7
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_5

#endif

#define BUILTIN_LED_GPIO GPIO_NUM_NC
#define BOOT_BUTTON_GPIO GPIO_NUM_9
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SPI_SCK_PIN GPIO_NUM_1
#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_2
#define DISPLAY_DC_PIN GPIO_NUM_0
#define DISPLAY_SPI_CS_PIN GPIO_NUM_21

// #define DISPLAY_WIDTH   320   //320
// #define DISPLAY_HEIGHT  240
// #define DISPLAY_MIRROR_X true
// #define DISPLAY_MIRROR_Y false
// #define DISPLAY_SWAP_XY true

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_20
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define UART_ECHO_TXD GPIO_NUM_13
#define UART_ECHO_RXD GPIO_NUM_12
#define UART_ECHO_RTS (-1)
#define UART_ECHO_CTS (-1)

#define ECHO_UART_PORT_NUM UART_NUM_1
#define ECHO_UART_BAUD_RATE (9600)
#define BUF_SIZE (1024)

// 修改屏幕显示尺寸
#define EP15_ENABLE 0
#define EP24_AND_EP28_AND_EP32_ENABLE 0
#define EP35_AND_EP40_ENABLE 0
#define EP1331G_ENABLE 0
#define EP1831T_ENABLE 1


#define LCD_TYPE_GC9A01_SERIAL
#if EP15_ENABLE
#define DISPLAY_WIDTH 240  // 240
#define DISPLAY_HEIGHT 240 // 240
// 控制显示区域水平翻转
#define DISPLAY_MIRROR_X false // true
// 控制显示区域垂直翻转(只包括显示区域,状态显示栏未翻转)
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false // false
#define DISPLAY_INVERT_COLOR false

#elif EP24_AND_EP28_AND_EP32_ENABLE
#define DISPLAY_WIDTH 240      // 240
#define DISPLAY_HEIGHT 320     // 240
#define DISPLAY_MIRROR_X false // true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false // false
#define DISPLAY_INVERT_COLOR false

#elif EP35_AND_EP40_ENABLE
#define DISPLAY_WIDTH 320     // 240
#define DISPLAY_HEIGHT 480    // 240
#define DISPLAY_MIRROR_X true // true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false // false
#define DISPLAY_INVERT_COLOR true

#elif EP1831T_ENABLE
#define DISPLAY_WIDTH 360      // 240
#define DISPLAY_HEIGHT 360     // 240
#define DISPLAY_MIRROR_X false // true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false // false
#define DISPLAY_INVERT_COLOR true

#elif EP1331G_ENABLE
#define DISPLAY_WIDTH 240     // 240
#define DISPLAY_HEIGHT 240    // 240
#define DISPLAY_MIRROR_X true // true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false // false
#define DISPLAY_INVERT_COLOR true
#endif

#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0

#endif // _BOARD_CONFIG_H_